version: '2'

services:
  ca0:
    container_name: ca.foo.com
    extends:
      file: base/base-ca.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY  
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem
    command: sh -c "fabric-ca-server start ${V11_IDENTITIES_ALLOWREMOVE} ${V11_AFFILIATIONS_ALLOWREMOVE} --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d"
    #command: sh -c "fabric-ca-server start -n ca-org1 ${V11_IDENTITIES_ALLOWREMOVE} ${V11_AFFILIATIONS_ALLOWREMOVE} --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw ${HYPERLEDGER_FABRIC_ENABLE_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -d"
    ports:
      - "7054:7054"
    volumes:
      - ./e2e-network/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org1.foo.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro

  ca1:
    container_name: ca.bar.com
    extends:
      file: base/base-ca.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem
    command: sh -c "fabric-ca-server start --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d"
    #command: sh -c "fabric-ca-server start --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw ${HYPERLEDGER_FABRIC_ENABLE_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -d"
    ports:
      - "8054:7054"
    volumes:
      - ./e2e-network/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org2.bar.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
      
  zookeeper0:
    container_name: zookeeper0
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1

  zookeeper1:
    container_name: zookeeper1
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2

  zookeeper2:
    container_name: zookeeper2
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3

  kafka0:
    container_name: kafka0
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka1:
    container_name: kafka1
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka2:
    container_name: kafka2
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka3:
    container_name: kafka3
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  orderer.simple.com:
    container_name: orderer.simple.com
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.simple.com
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  peer0.org1.foo.com:
    container_name: peer0.org1.foo.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org1.foo.com
    depends_on:
      - orderer.simple.com  

  peer1.org1.foo.com:
    container_name: peer1.org1.foo.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.org1.foo.com
    depends_on:
      - orderer.simple.com
      - peer0.org1.foo.com  

  peer0.org2.bar.com:
    container_name: peer0.org2.bar.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org2.bar.com
    depends_on:
      - orderer.simple.com  

  peer1.org2.bar.com:
    container_name: peer1.org2.bar.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.org2.bar.com
    depends_on:
      - orderer.simple.com
      - peer0.org2.bar.com  
  
  configtxlator:
    image: hyperledger/fabric-tools${IMAGE_TAG_FABRIC}
    container_name: configtxlator.com
    ports:
      - "7059:7059"
    command: /usr/local/bin/configtxlator start

  ccenv:
    image: hyperledger/fabric-ccenv${IMAGE_TAG_FABRIC}
    container_name: chaincode.env.com

  visualizer:
    container_name: visualizer.com
    extends:
      file: base/base-visualizer.yaml
      service: visualizer-base
    ports:
      - "8080:8080"
    #deploy:
      #placement:
        #constraints: [node.role == manager]