#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:
  ca0:
    image: hyperledger/fabric-ca${IMAGE_TAG_FABRIC_CA}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "7054:7054"
    command: /bin/bash -c "./scripts/check-files.sh ca0"
    volumes:
      - ./e2e-2orgs/${FAB_CONFIG_GEN_VERS}/crypto-config/peerOrganizations/org1.foo.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
      - ./e2e-2orgs/scripts/${FAB_CONFIG_GEN_VERS}:/scripts
    container_name: ca.foo.com

  ca1:
    image: hyperledger/fabric-ca${IMAGE_TAG_FABRIC_CA}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "8054:7054"
    command: /bin/bash -c "./scripts/check-files.sh ca1"
    volumes:
      - ./e2e-2orgs/${FAB_CONFIG_GEN_VERS}/crypto-config/peerOrganizations/org2.bar.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
      - ./e2e-2orgs/scripts/${FAB_CONFIG_GEN_VERS}:/scripts
    container_name: ca.bar.com

  orderer.simple.com:
    container_name: orderer.simple.com
    image: hyperledger/fabric-orderer${IMAGE_TAG_FABRIC}
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=${ORG_HYPERLEDGER_FABRIC_SDKTEST_INTEGRATIONTESTS_TLS}
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=${ORG_HYPERLEDGER_FABRIC_SDKTEST_INTEGRATIONTESTS_CLIENT_AUTH_REQUIRED}
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS=[/etc/hyperledger/msp/peerOrg1/msp/tlscacerts/tlsca.org1.foo.com-cert.pem, /etc/hyperledger/msp/peerOrg2/msp/tlscacerts/tlsca.org2.bar.com-cert.pem]
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
      - ORDERER_GENERAL_AUTHENTICATION_TIMEWINDOW=3600s #Not for production -- remove.
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: /bin/bash -c "/scripts/check-files.sh orderer"
    volumes:
     - ./e2e-2orgs/${FAB_CONFIG_GEN_VERS}/channel-artifacts:/etc/hyperledger/configtx:ro
     - ./e2e-2orgs/${FAB_CONFIG_GEN_VERS}/crypto-config/ordererOrganizations/simple.com/orderers/orderer.simple.com/:/etc/hyperledger/msp/orderer:ro
     - ./e2e-2orgs/${FAB_CONFIG_GEN_VERS}/crypto-config/peerOrganizations/org1.foo.com/peers/peer0.org1.foo.com/:/etc/hyperledger/msp/peerOrg1:ro
     - ./e2e-2orgs/${FAB_CONFIG_GEN_VERS}/crypto-config/peerOrganizations/org2.bar.com/peers/peer0.org2.bar.com/:/etc/hyperledger/msp/peerOrg2:ro
     - ./e2e-2orgs/scripts/${FAB_CONFIG_GEN_VERS}:/scripts
    ports:
      - 7050:7050

  peer0.org1.foo.com:
    container_name: peer0.org1.foo.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.foo.com
      - CORE_PEER_ADDRESS=peer0.org1.foo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.foo.com:7051
      #- CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=Org1MSP

      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/msp/cacerts/ca.org1.foo.com-cert.pem
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org1.foo.com-cert.pem
    volumes:
      - /var/run/:/host/var/run/
      - ./e2e-2orgs/${FAB_CONFIG_GEN_VERS}/crypto-config/peerOrganizations/org1.foo.com/peers/peer0.org1.foo.com/:/etc/hyperledger/msp/peer:ro
      - ./e2e-2orgs/scripts/${FAB_CONFIG_GEN_VERS}:/scripts
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer.simple.com
    #command: /bin/bash -c '/scripts/check-files.sh 4'

  peer1.org1.foo.com:
    container_name: peer1.org1.foo.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.foo.com
      - CORE_PEER_ADDRESS=peer1.org1.foo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.foo.com:7051
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.foo.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP

      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/msp/cacerts/ca.org1.foo.com-cert.pem
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org1.foo.com-cert.pem
    volumes:
         - /var/run/:/host/var/run/
         - ./e2e-2orgs/${FAB_CONFIG_GEN_VERS}/crypto-config/peerOrganizations/org1.foo.com/peers/peer1.org1.foo.com/:/etc/hyperledger/msp/peer:ro
         - ./e2e-2orgs/scripts/${FAB_CONFIG_GEN_VERS}:/scripts
    ports:
       - 7056:7051
       - 7058:7053
    depends_on:
       - orderer.simple.com
       - peer0.org1.foo.com
    #command: /bin/bash -c '/scripts/check-files.sh 5'  

  peer0.org2.bar.com:
    container_name: peer0.org2.bar.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.bar.com
      - CORE_PEER_ADDRESS=peer0.org2.bar.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.bar.com:8051
      #- CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=Org2MSP
      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/msp/cacerts/ca.org2.bar.com-cert.pem
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org2.bar.com-cert.pem
    volumes:
      - /var/run/:/host/var/run/
      - ./e2e-2orgs/${FAB_CONFIG_GEN_VERS}/crypto-config/peerOrganizations/org2.bar.com/peers/peer0.org2.bar.com/:/etc/hyperledger/msp/peer:ro
      - ./e2e-2orgs/scripts/${FAB_CONFIG_GEN_VERS}:/scripts
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer.simple.com
    #command: /bin/bash -c '/scripts/check-files.sh 6'
 

  peer1.org2.bar.com:
    container_name: peer1.org2.bar.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.bar.com
      - CORE_PEER_ADDRESS=peer1.org2.bar.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.bar.com:8051
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.bar.com:8051
      - CORE_PEER_LOCALMSPID=Org2MSP
      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/msp/cacerts/ca.org2.bar.com-cert.pem
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org2.bar.com-cert.pem
    volumes:
         - /var/run/:/host/var/run/
         - ./e2e-2orgs/${FAB_CONFIG_GEN_VERS}/crypto-config/peerOrganizations/org2.bar.com/peers/peer1.org2.bar.com/:/etc/hyperledger/msp/peer:ro
         - ./e2e-2orgs/scripts/${FAB_CONFIG_GEN_VERS}:/scripts
    ports:
       - 8056:7051
       - 8058:7053
    depends_on:
       - orderer.simple.com
       - peer0.org2.bar.com
    #command: /bin/bash -c '/scripts/check-files.sh 7'


  configtxlator:
    image: hyperledger/fabric-tools${IMAGE_TAG_FABRIC}
    ports:
      - "7059:7059"
    command: /usr/local/bin/configtxlator start
    container_name: configtxlator.com

  ccenv:
    image: hyperledger/fabric-ccenv${IMAGE_TAG_FABRIC}

