# hyperledger fabric network generator tools
# Copyright by @hoojo
# hoojo.me@gmail.com create by 2018-09-12
# @changelog hyperledger fabric network generator tools orderer & peer template defined


version: '3.6'

#-----------------------------------------------------------------------------------
# base service yaml
#-----------------------------------------------------------------------------------
x-base-services:
  orderer-base: &orderer-base
    image: hyperledger/fabric-orderer${IMAGE_TAG_FABRIC}
    environment: &orderer-env-common
      ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0

      ORDERER_GENERAL_GENESISMETHOD: file
      ORDERER_GENERAL_GENESISFILE: /etc/hyperledger/configtx/genesis.block
      ORDERER_GENERAL_LOCALMSPDIR: /etc/hyperledger/msp/orderer/msp
      
      # enabled TLS
      ORDERER_GENERAL_TLS_ENABLED: ${HYPERLEDGER_FABRIC_ENABLE_TLS}
      ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED: ${HYPERLEDGER_FABRIC_ENABLE_CLIENT_AUTH_REQUIRED}
      ORDERER_GENERAL_TLS_PRIVATEKEY: /etc/hyperledger/msp/orderer/tls/server.key
      ORDERER_GENERAL_TLS_CERTIFICATE: /etc/hyperledger/msp/orderer/tls/server.crt
      ORDERER_GENERAL_TLS_ROOTCAS: "[/etc/hyperledger/msp/orderer/tls/ca.crt]"
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    deploy:
      #mode: global
      mode: replicated
      replicas: 4
      #resources:
        #limits:
          #cpus: "0.5"
          #memory: 5000M
      restart_policy:
        condition: on-failure
      #placement:
      #  constraints: [node.role == manager]
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3


  peer-base: &peer-base
    image: hyperledger/fabric-peer${IMAGE_TAG_FABRIC}
    environment: &peer-env-common
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: fabric_blockchain_net
      #CORE_LOGGING_LEVEL: ERROR
      CORE_LOGGING_LEVEL: DEBUG
      # endorser enabled
      CORE_PEER_ENDORSER_ENABLED: "true"
      CORE_PEER_GOSSIP_USELEADERELECTION: "true"
      CORE_PEER_GOSSIP_ORGLEADER: "false"
      # channel service enalbed
      CORE_PEER_CHANNELSERVICE_ENABLED: "true"
      # The following setting skips the gossip handshake since we are not doing mutual TLS
      CORE_PEER_MSPCONFIGPATH: /etc/hyperledger/msp/peer/msp
      # skip phandshake
      CORE_PEER_GOSSIP_SKIPHANDSHAKE: "true"
      
      ########## profile enabled: true
      CORE_PEER_PROFILE_ENABLED: "false"
      CORE_PEER_TLS_ENABLED: ${HYPERLEDGER_FABRIC_ENABLE_TLS}
      CORE_PEER_TLS_CLIENTAUTHREQUIRED: ${HYPERLEDGER_FABRIC_ENABLE_CLIENT_AUTH_REQUIRED}
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/msp/peer/tls/server.crt
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/msp/peer/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/msp/peer/tls/ca.crt

      # NOTE BOTH below should never be used in production.
      CORE_PEER_AUTHENTICATION_TIMEWINDOW: 3600s
      CORE_PEER_EVENTS_TIMEWINDOW: 3600s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    deploy:
      #mode: global
      mode: replicated
      replicas: 4
      #resources:
        #limits:
          #cpus: "0.25"
          #memory: 2500M
      restart_policy:
        condition: on-failure


services:
#-----------------------------------------------------------------------------------
# Orderer service yaml
#-----------------------------------------------------------------------------------
  orderer:
    container_name: orderer.hoojo.me
    <<: *orderer-base
    environment:
      <<: *orderer-env-common
      ORDERER_GENERAL_LOCALMSPID: OrdererMSP
      ORDERER_GENERAL_LOGLEVEL: debug
      ORDERER_GENERAL_TLS_CLIENTROOTCAS: "[/etc/hyperledger/msp/peerOrg1/msp/tlscacerts/tlsca.org1.hoojo.me-cert.pem, /etc/hyperledger/msp/peerOrg2/msp/tlscacerts/tlsca.org2.hoojo.me-cert.pem]"
      GRPC_TRACE: all=true,
      GRPC_VERBOSITY: debug
      ORDERER_GENERAL_AUTHENTICATION_TIMEWINDOW: 3600s #Not for production -- remove.

      # new add Kafka config
      ORDERER_KAFKA_RETRY_SHORTINTERVAL: 1s
      ORDERER_KAFKA_RETRY_SHORTTOTAL: 60s
      ORDERER_KAFKA_VERBOSE: "true"
    volumes:
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/channel-artifacts:/etc/hyperledger/configtx:ro
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/ordererOrganizations/hoojo.me/orderers/orderer.hoojo.me/:/etc/hyperledger/msp/orderer:ro
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org1.hoojo.me/peers/one.org1.hoojo.me/:/etc/hyperledger/msp/peerOrg1:ro
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org2.hoojo.me/peers/three.org2.hoojo.me/:/etc/hyperledger/msp/peerOrg2:ro

    ports:
      - 7050:7050



#-----------------------------------------------------------------------------------
# Org1 service yaml
#-----------------------------------------------------------------------------------
  one_org1:
    container_name: one.org1.hoojo.me
    <<: *peer-base
    environment:
      <<: *peer-env-common
      CORE_PEER_ID: one.org1.hoojo.me
      CORE_PEER_ADDRESS: one.org1.hoojo.me:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: one.org1.hoojo.me:7051
      #CORE_PEER_GOSSIP_ORGLEADER: true
      CORE_PEER_LOCALMSPID: Org1MSP

      #CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/msp/peer/msp/cacerts/ca.org1.hoojo.me-cert.pem
      CORE_PEER_TLS_CLIENTROOTCAS_FILES: /etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org1.hoojo.me-cert.pem

      # NEW ADD
      CORE_PEER_CHAINCODEADDRESS: one.org1.hoojo.me:7052
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_BOOTSTRAP: one.org1.hoojo.me:7051
      #CORE_PEER_GOSSIP_BOOTSTRAP: peer1.org1.hoojo.me:7051

      # v1.2
      # CORE_PEER_LISTENADDRESS: one.org1.hoojo.me:7051
      CORE_PEER_GOSSIP_ENDPOINT: one.org1.hoojo.me:7051
      CORE_PEER_EVENTS_ADDRESS: 0.0.0.0:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org1.hoojo.me/peers/one.org1.hoojo.me/:/etc/hyperledger/msp/peer:ro
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    depends_on:
      - orderer


  two_org1:
    container_name: two.org1.hoojo.me
    <<: *peer-base
    environment:
      <<: *peer-env-common
      CORE_PEER_ID: two.org1.hoojo.me
      CORE_PEER_ADDRESS: two.org1.hoojo.me:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: two.org1.hoojo.me:7051
      #CORE_PEER_GOSSIP_ORGLEADER: true
      CORE_PEER_LOCALMSPID: Org1MSP

      #CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/msp/peer/msp/cacerts/ca.org1.hoojo.me-cert.pem
      CORE_PEER_TLS_CLIENTROOTCAS_FILES: /etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org1.hoojo.me-cert.pem

      # NEW ADD
      CORE_PEER_CHAINCODEADDRESS: two.org1.hoojo.me:7052
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_BOOTSTRAP: two.org1.hoojo.me:7051
      #CORE_PEER_GOSSIP_BOOTSTRAP: peer1.org1.hoojo.me:7051

      # v1.2
      # CORE_PEER_LISTENADDRESS: two.org1.hoojo.me:7051
      CORE_PEER_GOSSIP_ENDPOINT: two.org1.hoojo.me:7051
      CORE_PEER_EVENTS_ADDRESS: 0.0.0.0:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org1.hoojo.me/peers/two.org1.hoojo.me/:/etc/hyperledger/msp/peer:ro
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053
    depends_on:
      - orderer
      - one_org1


#-----------------------------------------------------------------------------------
# Org2 service yaml
#-----------------------------------------------------------------------------------
  three_org2:
    container_name: three.org2.hoojo.me
    <<: *peer-base
    environment:
      <<: *peer-env-common
      CORE_PEER_ID: three.org2.hoojo.me
      CORE_PEER_ADDRESS: three.org2.hoojo.me:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: three.org2.hoojo.me:7051
      #CORE_PEER_GOSSIP_ORGLEADER: true
      CORE_PEER_LOCALMSPID: Org2MSP

      #CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/msp/peer/msp/cacerts/ca.org2.hoojo.me-cert.pem
      CORE_PEER_TLS_CLIENTROOTCAS_FILES: /etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org2.hoojo.me-cert.pem

      # NEW ADD
      CORE_PEER_CHAINCODEADDRESS: three.org2.hoojo.me:7052
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_BOOTSTRAP: three.org2.hoojo.me:7051
      #CORE_PEER_GOSSIP_BOOTSTRAP: peer1.org2.hoojo.me:7051

      # v1.2
      # CORE_PEER_LISTENADDRESS: three.org2.hoojo.me:7051
      CORE_PEER_GOSSIP_ENDPOINT: three.org2.hoojo.me:7051
      CORE_PEER_EVENTS_ADDRESS: 0.0.0.0:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org2.hoojo.me/peers/three.org2.hoojo.me/:/etc/hyperledger/msp/peer:ro
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053
    depends_on:
      - orderer


  four_org2:
    container_name: four.org2.hoojo.me
    <<: *peer-base
    environment:
      <<: *peer-env-common
      CORE_PEER_ID: four.org2.hoojo.me
      CORE_PEER_ADDRESS: four.org2.hoojo.me:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: four.org2.hoojo.me:7051
      #CORE_PEER_GOSSIP_ORGLEADER: true
      CORE_PEER_LOCALMSPID: Org2MSP

      #CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/msp/peer/msp/cacerts/ca.org2.hoojo.me-cert.pem
      CORE_PEER_TLS_CLIENTROOTCAS_FILES: /etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org2.hoojo.me-cert.pem

      # NEW ADD
      CORE_PEER_CHAINCODEADDRESS: four.org2.hoojo.me:7052
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_BOOTSTRAP: four.org2.hoojo.me:7051
      #CORE_PEER_GOSSIP_BOOTSTRAP: peer1.org2.hoojo.me:7051

      # v1.2
      # CORE_PEER_LISTENADDRESS: four.org2.hoojo.me:7051
      CORE_PEER_GOSSIP_ENDPOINT: four.org2.hoojo.me:7051
      CORE_PEER_EVENTS_ADDRESS: 0.0.0.0:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org2.hoojo.me/peers/four.org2.hoojo.me/:/etc/hyperledger/msp/peer:ro
    ports:
      - 10051:7051
      - 10052:7052
      - 10053:7053
    depends_on:
      - orderer
      - three_org2


