version: '2'

services:
  zookeeper:
    extends:
      file: base-kafka.yaml
      service: zookeeper-base
    environment:
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888    
    ports:
      - 2181
      - 2888
      - 3888
    
  kafka:
    extends:
      file: base-kafka.yaml
      service: kafka-base
    environment:
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    ports:
      - 9092  

  orderer.simple.com:
    container_name: orderer.simple.com
    extends:
      file: base-orderer.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS=[/etc/hyperledger/msp/peerOrg1/msp/tlscacerts/tlsca.org1.foo.com-cert.pem, /etc/hyperledger/msp/peerOrg2/msp/tlscacerts/tlsca.org2.bar.com-cert.pem]
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
      - ORDERER_GENERAL_AUTHENTICATION_TIMEWINDOW=3600s #Not for production -- remove.
      
      # new add Kafka config
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
    volumes:
      - ../e2e-network/${FABRIC_NETWORK_CONFIGTX_VERSION}/channel-artifacts:/etc/hyperledger/configtx:ro
      - ../e2e-network/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/ordererOrganizations/simple.com/orderers/orderer.simple.com/:/etc/hyperledger/msp/orderer:ro
      - ../e2e-network/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org1.foo.com/peers/peer0.org1.foo.com/:/etc/hyperledger/msp/peerOrg1:ro
      - ../e2e-network/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org2.bar.com/peers/peer0.org2.bar.com/:/etc/hyperledger/msp/peerOrg2:ro
    ports:
      - 7050:7050

  peer0.org1.foo.com:
    container_name: peer0.org1.foo.com
    extends:
      file: base-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.foo.com
      - CORE_PEER_ADDRESS=peer0.org1.foo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.foo.com:7051
      #- CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=Org1MSP

      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/msp/cacerts/ca.org1.foo.com-cert.pem
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org1.foo.com-cert.pem
      
      # NEW ADD
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.foo.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      
      # v1.2
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.org1.foo.com:7051
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
    volumes:
      - ../e2e-network/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org1.foo.com/peers/peer0.org1.foo.com/:/etc/hyperledger/msp/peer:ro
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer1.org1.foo.com:
    container_name: peer1.org1.foo.com
    extends:
      file: base-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.foo.com
      - CORE_PEER_ADDRESS=peer1.org1.foo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.foo.com:7051
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.foo.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP

      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/msp/cacerts/ca.org1.foo.com-cert.pem
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org1.foo.com-cert.pem
      
      # NEW ADD
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.foo.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.foo.com:7051
      
      # v1.2
      - CORE_PEER_LISTENADDRESS=peer1.org1.foo.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.org1.foo.com:7051
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
    volumes:
      - ../e2e-network/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org1.foo.com/peers/peer1.org1.foo.com/:/etc/hyperledger/msp/peer:ro
    ports:
      - 7056:7051
      - 7057:7052
      - 7058:7053

  peer0.org2.bar.com:
    container_name: peer0.org2.bar.com
    extends:
      file: base-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.bar.com
      - CORE_PEER_ADDRESS=peer0.org2.bar.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.bar.com:7051
      #- CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=Org2MSP
      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/msp/cacerts/ca.org2.bar.com-cert.pem
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org2.bar.com-cert.pem
      
      # NEW ADD
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.bar.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      
      # v1.2
      - CORE_PEER_LISTENADDRESS=peer0.org2.bar.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.org2.bar.com:7051
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.bar.com:7051
    volumes:
      - ../e2e-network/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org2.bar.com/peers/peer0.org2.bar.com/:/etc/hyperledger/msp/peer:ro
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053

  peer1.org2.bar.com:
    container_name: peer1.org2.bar.com
    extends:
      file: base-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.bar.com
      - CORE_PEER_ADDRESS=peer1.org2.bar.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.bar.com:7051
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.bar.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/msp/cacerts/ca.org2.bar.com-cert.pem
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.org2.bar.com-cert.pem
      
      # NEW ADD
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.bar.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.bar.com:7051
      
      # v1.2
      - CORE_PEER_LISTENADDRESS=peer1.org2.bar.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.org1.bar.com:7051
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
    volumes:
      - ../e2e-network/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org2.bar.com/peers/peer1.org2.bar.com/:/etc/hyperledger/msp/peer:ro
    ports:
      - 8056:7051
      - 8057:7052
      - 8058:7053

