version: '3.6'

#-----------------------------------------------------------------------------------
# base service yaml
#-----------------------------------------------------------------------------------
x-base-services:
  ca: &ca-base
    image: hyperledger/fabric-ca${IMAGE_TAG_FABRIC_CA}
    environment: &ca-env-common
      FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
      FABRIC_CA_SERVER_TLS_ENABLED: ${HYPERLEDGER_FABRIC_ENABLE_TLS}
    expose:
      - "7054"
    deploy: &ca-deploy-common
      #replicas: 3
      resources:
        limits:
          cpus: "0.3"
      #    memory: 2000M
      restart_policy:
        condition: on-failure   


#-----------------------------------------------------------------------------------
# networks yaml
#-----------------------------------------------------------------------------------
networks:
  blockchain_net:
    driver: overlay
    attachable: true


#-----------------------------------------------------------------------------------
# core service yaml
#-----------------------------------------------------------------------------------
services:
  ca0:
    container_name: ca.foo.com
    <<: *ca-base
    deploy:
      <<: *ca-deploy-common
      placement:
        constraints:
          - node.hostname == localhost.localdomain
    environment:
      <<: *ca-env-common
      FABRIC_CA_SERVER_CA_NAME: ca-org1
      FABRIC_CA_SERVER_TLS_KEYFILE: /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY  
      FABRIC_CA_SERVER_TLS_CERTFILE: /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem
    command: sh -c "fabric-ca-server start ${V11_IDENTITIES_ALLOWREMOVE} ${V11_AFFILIATIONS_ALLOWREMOVE} --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d"
    #command: sh -c "fabric-ca-server start -n ca-org1 ${V11_IDENTITIES_ALLOWREMOVE} ${V11_AFFILIATIONS_ALLOWREMOVE} --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw ${HYPERLEDGER_FABRIC_ENABLE_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -d"
    ports:
      - "7054:7054"
    volumes:
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org1.foo.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    networks:
      blockchain_net:
        aliases:
          - ca.foo.com           

  ca1:
    container_name: ca.bar.com
    <<: *ca-base
    deploy:
      <<: *ca-deploy-common
      placement:
        constraints:
          - node.hostname == localhost.localdomain
    environment:
      <<: *ca-env-common
      FABRIC_CA_SERVER_CA_NAME: ca-org2
      FABRIC_CA_SERVER_TLS_KEYFILE: /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
      FABRIC_CA_SERVER_TLS_CERTFILE: /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem
    command: sh -c "fabric-ca-server start --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d"
    #command: sh -c "fabric-ca-server start --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw ${HYPERLEDGER_FABRIC_ENABLE_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -d"
    ports:
      - "8054:7054"
    volumes:
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org2.bar.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    networks:
      blockchain_net:
        aliases:
          - ca.bar.com        
  
  configtxlator:
    container_name: configtxlator.com
    image: hyperledger/fabric-tools${IMAGE_TAG_FABRIC}    
    command: /usr/local/bin/configtxlator start
    ports:
      - "7059:7059"
    networks:
      blockchain_net:
        aliases:
          - configtxlator.com
    deploy:
      #replicas: 3
      resources:
        limits:
          cpus: "0.2"
      #    memory: 500M
      restart_policy:
        condition: on-failure  
      placement:
        constraints: [node.role == worker]

  ccenv:
    container_name: ccenv
    image: hyperledger/fabric-ccenv${IMAGE_TAG_FABRIC}
    networks:
      - blockchain_net
    deploy:
      #replicas: 3
      resources:
        limits:
          cpus: "0.25"
      #    memory: 2000M
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  zookeeper0:
    networks:
      - blockchain_net    

  zookeeper1:
    networks:
      - blockchain_net

  zookeeper2:
    networks:
      - blockchain_net

  kafka0:
    networks:
      - blockchain_net 

  kafka1:
    networks:
      - blockchain_net
 
  kafka2:
    networks:
      - blockchain_net

  kafka3:
    networks:
      - blockchain_net

  orderer:    
    networks:
      blockchain_net:
        aliases:
          - orderer.simple.com

  peer0-org1:    
    networks:
      blockchain_net:
        aliases:
          - peer0.org1.foo.com   

  peer1-org1:    
    networks:
      blockchain_net:
        aliases:
          - peer1.org1.foo.com  

  peer0-org2:    
    networks:
      blockchain_net:
        aliases:
          - peer0.org2.bar.com  

  peer1-org2:    
    networks:
      blockchain_net:
        aliases:
          - peer1.org2.bar.com