version: '2.1'

services:
  couchdb0:
    container_name: couchdb0
    extends:
      file: base/base-couchdb.yaml
      service: couchdb-base
    # 5984 对外开放  
    ports:
      - "5984:5984"

  couchdb1:
    container_name: couchdb1
    extends:
      file: base/base-couchdb.yaml
      service: couchdb-base
    ports:
      - "6984:5984"

  couchdb2:
    container_name: couchdb2
    extends:
      file: base/base-couchdb.yaml
      service: couchdb-base
    ports:
      - "7984:5984"

  couchdb3:
    container_name: couchdb3
    extends:
      file: base/base-couchdb.yaml
      service: couchdb-base
    ports:
      - "8984:5984"

  peer0-org1:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb0
      
  peer1-org1:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb1
      
  peer0-org2:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb2
      
  peer1-org2:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb3
