version: '3.6'

networks:
  blockchain-net:
    driver: overlay
    attachable: true

services:
  zookeeper0:
    networks:
      - blockchain_net    

  zookeeper1:
    networks:
      - blockchain_net

  zookeeper2:
    networks:
      - blockchain_net

  kafka0:
    networks:
      - blockchain_net 

  kafka1:
    networks:
      - blockchain_net
 
  kafka2:
    networks:
      - blockchain_net

  kafka3:
    networks:
      - blockchain_net

  orderer:    
    networks:
      blockchain-net:
        aliases:
          - orderer.simple.com

  peer0-org1:    
    networks:
      blockchain-net:
        aliases:
          - peer0.org1.foo.com   

  peer1-org1:    
    networks:
      blockchain-net:
        aliases:
          - peer1.org1.foo.com  

  peer0-org2:    
    networks:
      blockchain-net:
        aliases:
          - peer0.org2.bar.com  

  peer1-org2:    
    networks:
      blockchain-net:
        aliases:
          - peer1.org2.bar.com  
  
  cli:
    image: hyperledger/fabric-tools${IMAGE_TAG_FABRIC}
    tty: true
    stdin_open: true    
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer      
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli

      - CORE_PEER_ADDRESS=peer0.org1.foo.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=${HYPERLEDGER_FABRIC_ENABLE_TLS}
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.foo.com/peers/peer0.org1.foo.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.foo.com/peers/peer0.org1.foo.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.foo.com/peers/peer0.org1.foo.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.foo.com/users/Admin@org1.foo.com/msp
    command: /bin/bash -c "./scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT"
    volumes:
      - /var/run/:/host/var/run/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts    