version: '3.6'

#-----------------------------------------------------------------------------------
# base service yaml
#-----------------------------------------------------------------------------------
x-base-services:
  couchdb: &couchdb-base
    image: hyperledger/fabric-couchdb${IMAGE_TAG_FABRIC_COUCHDB}
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    expose:
      - 5984
    networks:
      - blockchain_net  
    deploy: &couchdb-deploy-common
      #replicas: 3
      resources:
        limits:
          cpus: "0.25"
          #memory: 3000M
      restart_policy:
        condition: on-failure


#-----------------------------------------------------------------------------------
# couchdb & peer service yaml
#-----------------------------------------------------------------------------------
services:
  couchdb0:
    container_name: couchdb0
    <<: *couchdb-base
    deploy:
      <<: *couchdb-deploy-common
      placement:
        constraints:
          - node.hostname == dev-010
    ports:
      - "5984:5984"
    networks:
      blockchain_net:
        aliases:
          - couchdb0

  couchdb1:
    container_name: couchdb1
    <<: *couchdb-base
    deploy:
      <<: *couchdb-deploy-common
      placement:
        constraints:
          - node.hostname == dev-020
    #ports:
    #  - "6984:5984"
    networks:
      blockchain_net:
        aliases:
          - couchdb1

  couchdb2:
    container_name: couchdb2
    <<: *couchdb-base
    deploy:
      <<: *couchdb-deploy-common
      placement:
        constraints:
          - node.hostname == localhost.localdomain
    #ports:
    #  - "7984:5984"
    networks:
      blockchain_net:
        aliases:
          - couchdb2

  couchdb3:
    container_name: couchdb3
    <<: *couchdb-base
    deploy:
      <<: *couchdb-deploy-common
      placement:
        constraints:
          - node.hostname == dev-040
    #ports:
    #  - "8984:5984"
    networks:
      blockchain_net:
        aliases:
          - couchdb3

  peer0-org1:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb0
      
  peer1-org1:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb1  
      
  peer0-org2:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb2  
      
  peer1-org2:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb3  
