version: '2.1'

networks:
  blockchain_net:
    driver: overlay
    attachable: true

services:
  ca0:
    extends:
      file: base/base-ca.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY  
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem
    command: sh -c "fabric-ca-server start ${V11_IDENTITIES_ALLOWREMOVE} ${V11_AFFILIATIONS_ALLOWREMOVE} --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d"
    #command: sh -c "fabric-ca-server start -n ca-org1 ${V11_IDENTITIES_ALLOWREMOVE} ${V11_AFFILIATIONS_ALLOWREMOVE} --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw ${HYPERLEDGER_FABRIC_ENABLE_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -d"
    ports:
      - "7054:7054"
    volumes:
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org1.foo.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    networks:
      blockchain_net:
        aliases:
          - ca.foo.com    

  ca1:
    extends:
      file: base/base-ca.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem
    command: sh -c "fabric-ca-server start --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d"
    #command: sh -c "fabric-ca-server start --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw ${HYPERLEDGER_FABRIC_ENABLE_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -d"
    ports:
      - "8054:7054"
    volumes:
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org2.bar.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    networks:
      blockchain_net:
        aliases:
          - ca.bar.com  
      
  zookeeper0:
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
    networks:
      - blockchain_net

  zookeeper1:
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
    networks:
      - blockchain_net  

  zookeeper2:
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
    networks:
      - blockchain_net  

  kafka0:
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - blockchain_net  

  kafka1:
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - blockchain_net  

  kafka2:
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - blockchain_net  

  kafka3:
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - blockchain_net  

  orderer:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.simple.com
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      blockchain_net:
        aliases:
          - orderer.simple.com

  peer0-org1:
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org1.foo.com
    depends_on:
      - orderer
    networks:
      blockchain_net:
        aliases:
          - peer0.org1.foo.com   

  peer1-org1:
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.org1.foo.com
    depends_on:
      - orderer
      - peer0-org1 
    networks:
      blockchain_net:
        aliases:
          - peer1.org1.foo.com  

  peer0-org2:
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org2.bar.com
    depends_on:
      - orderer
    networks:
      blockchain_net:
        aliases:
          - peer0.org2.bar.com  

  peer1-org2:
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.org2.bar.com
    depends_on:
      - orderer
      - peer0-org2
    networks:
      blockchain_net:
        aliases:
          - peer1.org2.bar.com  
  
  configtxlator:
    image: hyperledger/fabric-tools${IMAGE_TAG_FABRIC}
    ports:
      - "7059:7059"
    command: /usr/local/bin/configtxlator start
    networks:
      blockchain_net:
        aliases:
          - configtxlator.com

  ccenv:
    image: hyperledger/fabric-ccenv${IMAGE_TAG_FABRIC}
    networks:
      - blockchain_net