version: "2.1"

networks:  
  #monitor_net:    
    #external:
    #  name: fabric-net
  external_monitor_net:
    external:
      name: monitor_net
      
services:
  visualizer:
    extends:
      file: base/base-visualizer.yaml
      service: visualizer-base
    
    networks:
      - external_monitor_net
      - blockchain_net
      
    ports:
      - "3100:8080"       