version: '3.6'

#-----------------------------------------------------------------------------------
# base service yaml
#-----------------------------------------------------------------------------------
x-base-services:
  couchdb: &couchdb-base
    image: hyperledger/fabric-couchdb${IMAGE_TAG_FABRIC_COUCHDB}
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    networks:
      - blockchain_net  
    expose:
      - 5984 


#-----------------------------------------------------------------------------------
# couchdb & peer service yaml
#-----------------------------------------------------------------------------------
services:
  couchdb0:
    <<: *couchdb-base
    ports:
      - "5984:5984"

  couchdb1:
    <<: *couchdb-base
    ports:
      - "6984:5984"

  couchdb2:
    <<: *couchdb-base
    ports:
      - "7984:5984"

  couchdb3:
    <<: *couchdb-base
    ports:
      - "8984:5984"

  peer0-org1:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      
  peer1-org1:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      
  peer0-org2:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      
  peer1-org2:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
